kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: kube-monitor
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus